-- CREATE DATATBASE IF IT DOES NOT ALREADY EXIST
CREATE DATABASE IF NOT EXISTS mcsp02donuts;

-- CONNECT TO DATABASE
USE mcsp02donuts;

-- CREATE DONUTS TABLE
-- WITH COLUMNS
CREATE TABLE IF NOT EXISTS donuts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    filling VARCHAR(25),
    stale TINYINT(1)
);

